FROM python:3.12.7

LABEL author="Sebastian Avendaño Rodriguez"

WORKDIR /service1/python

COPY ./requeriments.txt /service1/python/

RUN pip install --no-cache-dir -r /service1/python/requeriments.txt

COPY restaurant-reviews-bookings/restaurant-service /service1/python/

EXPOSE 8081

CMD ["pytest"]
