services:
  appjava:
    container_name: login-request-service
    build: 
      context: .
      dockerfile: Dockerfile.java
    ports:
      - "8080:8080"

  apppython:
    container_name: restaurant-review-service
    build: 
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8081:8081"

