services:

  app1:
    container_name: login-request-service
    build: 
      context: .
      dockerfile: Dockerfile.java
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_testing
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=testing
    depends_on:
      db:
        condition: service_healthy
        
  app2:
    container_name: restaurant-review-service
    build: 
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      

  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db_testing
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_PASSWORD: testing
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  db-data:
    external: false